#!/bin/python3

import cv2 
import numpy as np 
  
# Open the image. 
img = cv2.imread('chandler.jpg')

# Apply log transform.
gamma = 0.1
gamma_corrected = np.array(255*(img / 255) ** gamma, dtype = 'uint8')
cv2.imshow('gamma_transformed', gamma_corrected)

cv2.waitKey(0)
cv2.destroyAllWindows()
