#!/bin/python3

import cv2
import numpy as np

# path to input images are specified and
# images are loaded with imread command
image1 = cv2.imread('fire.png')
image2 = cv2.imread('capybara.jpg')

# cv2.addWeighted is applied over the
# image inputs with applied parameters
weightedSum = cv2.addWeighted(image1, 0.6, image2, 0.4, 0)

cv2.imshow('Weighted Image', weightedSum)

if cv2.waitKey(0) & 0xff == 27:
    cv2.destroyAllWindows()
